### ISSUE TITLE
Add functionality to the profile update form

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#198] opened 2022-09-12 15:32 UTC
![chrome_pRrRf0QjSq](https://user-images.githubusercontent.com/71513679/189694804-6eac1d04-1222-4a20-9a7e-e81571318dc5.png)

**Comment by Israel-Laguan** [comment] 2022-09-12 16:59
duplicate of #200, closing this one

**Closed as completed by Israel-Laguan** 2022-09-12 16:59 UTC
Labels: duplicate, DEV Check
