### ISSUE TITLE
Edit product

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#169] opened 2022-09-04 16:07 UTC
### Description
Currently, when I select a product it takes me to a form that is not the same as the create product form.
The form has no data for the selected product.
It also gives error when I try to send the data
### Screenchot
![chrome_OqWnktaiS0](https://user-images.githubusercontent.com/71513679/188322497-7d964075-8104-4e55-a831-d074714f2655.png)

### Steps to go

1. Go to 'Proveedores'
2. Click any provider
3. Click any product

### Acceptance Criteria

- [ ] The inputs should be filled with information about the selected product.
- [ ] When you click on save, you should edit the selected product.
- [ ] When you click on delete, you should delete the product.

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Eghinner** [comment] 2022-09-04 16:08
Blocked meanwhile https://github.com/Azordev/did-admin-panel/pull/136 and #168 is closed

**Comment by Israel-Laguan** [comment] 2022-09-12 04:16
User for a provider:
Username:
`00ROLLUX`
Password:
`ROLLUX`

**Comment by Israel-Laguan** [comment] 2022-09-12 05:46
> Blocked meanwhile #136 and #168 is closed

#136 closed, I think this can be worked without #168

**Comment by Israel-Laguan** [comment] 2022-09-12 17:00
Not sure if a duplicate of #198 and #200, @Eghinner please confirm

**Comment by Eghinner** [comment] 2022-09-12 17:03
yes

**Closed as completed** 2022-09-13 15:20 UTC
Labels: EE-3, priority high, DEV Check, QA check
